# this needs to run as root
# Development packages
# We are only installing these packages because we will be compiling JWM from GIT
# Test this  x11proto-randr-dev and other x11proto* packages already installed
# Test: xserver-xorg-dev xserver-xorg-input-evdev xserver-xorg-input-evdev-dev xserver-xorg-input-libinput-dev

#!/bin/bash

apt-get --no-install-recommends --no-install-suggests install libpango1.0-dev libpangomm-1.4-dev libcogl-dev libcogl-pango-dev libcoin-dev libegl-dev libegl1-mesa-dev libepoxy-dev libftgl-dev libgbm-dev libgl1-mesa-dev libgles-dev libgles2-mesa-dev libglw1-mesa-dev libglew-dev libglu1-mesa-dev libglvnd-dev libopengl-dev libwayland-dev libxgks-dev libxkbcommon-dev libxklavier-dev libxml2-dev libxaw3dxft8-dev libltdl-dev libbsd-dev libcourier-unicode-dev libcxxtools-dev libghc-iconv-dev libgmp-dev libiconv-hook-dev libncurses-dev libncurses5-dev libtranscript-dev lua-iconv-dev win-iconv-mingw-w64-dev libcairomm-1.0-dev libdatrie-dev libfribidi-dev libglibmm-2.4-dev libgraphite2-dev libharfbuzz-dev libicu-dev libpangox-1.0-dev libsigc++-2.0-dev libthai-dev  autotools-dev libblkid-dev libbrotli-dev libcairo-5c-dev libcairo2-dev libdmx-dev libdrm-dev libexpat1-dev libffi-dev libfontconfig-dev libfontconfig1-dev libfontenc-dev libfreetype-dev libfreetype6-dev libfs-dev libgdk-pixbuf-2.0-dev libgdk-pixbuf-xlib-2.0-dev libgdk-pixbuf2.0-dev libgl-dev libglib2.0-dev libglib2.0-dev-bin libglx-dev libice-dev libjpeg9-dev libmount-dev libpciaccess-dev libpcre2-dev libpixman-1-dev libpng-dev libpthread-stubs0-dev librsvg2-dev libselinux1-dev libsepol1-dev libsm-dev libturbojpeg0-dev libx11-xcb-dev libxaw7-dev libxcb-render0-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev  libxext-dev libxfixes-dev libxfont-dev libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86dga-dev libxxf86vm-dev libva-dev libvdpau-dev libigfxcmrt-dev libxshmfence-dev libxslt1-dev libpcaudio-dev libgtkgl2.0-dev libgtkglext1-dev libgtkglextmm-x11-1.2-dev libopenal-dev libopenlayer-dev libygl4-dev libmojoshader-dev uuid-dev xorg-dev libpaps-dev zlib1g-dev mesa-common-dev 
